In [1]:
import numpy as np

In [31]:
guess_list = np.load('./gym_wordle/data/guess_list.npy').astype(np.int32)
solution_list = np.load('./gym_wordle/data/solution_list.npy')

In [3]:
allowed_list

array([[ 1,  1,  8,  5,  4],
       [ 1,  1, 12,  9,  9],
       [ 1,  1, 18,  7,  8],
       ...,
       [26, 25,  7, 15, 14],
       [26, 25, 13,  5, 19],
       [26, 25, 13,  9,  3]])

In [4]:
allowed_list.shape

(12972, 5)

In [5]:
allowed_list[0]

array([1, 1, 8, 5, 4])

In [6]:
allowed_list[0] + 96

array([ 97,  97, 104, 101, 100])

In [9]:
for i in allowed_list[0] + 96:
    print(chr(i))

a
a
h
e
d


In [15]:
guess_words = []
for word_index in range(guess_list.shape[0]):
    word_array = []
    for char_index in range(5):
        word_array.append(chr(guess_list[word_index][char_index] + 96))
    guess_words.append(''.join(word_array))

In [19]:
solution_words = []
for word_index in range(solution_list.shape[0]):
    word_array = []
    for char_index in range(5):
        word_array.append(chr(solution_list[word_index][char_index] + 96))
    solution_words.append(''.join(word_array))

In [22]:
[x for x in solution_words if x not in guess_words]

[]

In [24]:
np.random.choice(list(solution_list))

ValueError: a must be 1-dimensional

In [26]:
solution_list[np.random.randint(solution_list.shape[0])]

array([1, 2, 9, 4, 5])

In [29]:
solution_list.dtype()

TypeError: 'numpy.dtype[int64]' object is not callable